apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app01
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - gw-route.yaml
  - np.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: ti-httpbin
