apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vm-system-netpols.yaml
  - cert-manager-netpols.yaml
  - gw-system-netpols.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: ti-httpbin
